# SITE CONFIGURATION
title: ISMIR 2020  # your site title
author: Evan Savage # You :P
description: > # Meta description of Homepage
  International Society for Music Information Retrieval Conference
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Your Name
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  # - {name: 'Home', link: '/'}
  - {name: 'Program', link: 'https://program.ismir2020.org/calendar'}
  - {name: 'For Participants', link: '/participants'}
  - {name: 'Registration', link: '/registration'}
  - {name: 'Dates', link: '/dates'}
  - {name: 'Events', link: '/events'}
  - {name: 'Organizers', link: '/organizers'}
  - {name: 'Call for Sponsors', link: '/sponsors'}
  - {name: 'WiMIR', link: '/WiMIR'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: ISMIR_Homepage_HERO_IMAGE.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: your-email@domain.com # email for form submission

twitter_username: ismir2020 # replace with your_twitter_username or comment to remove link from footer
github_username:  ismir # replace with your_github_username or comment to remove link from footer
wikipedia: https://en.wikipedia.org/wiki/International_Society_for_Music_Information_Retrieval # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  cards:
    output: true


# sass:
#     sass_dir: _sass
